name: CI/CD - Fiap Video Processor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME_API: dmiyamoto86/fiap-api
  IMAGE_NAME_WORKER: dmiyamoto86/fiap-worker

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./FiapServiceVideoProcessor.WebApi

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish API
      run: dotnet publish -c Release -o out

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push API Docker image
      run: |
        docker build -t $REGISTRY/${{ env.IMAGE_NAME_API }}:latest -f FiapServiceVideoProcessor.WebApi/Dockerfile .
        docker push $REGISTRY/${{ env.IMAGE_NAME_API }}:latest

    - name: Build and push Worker Docker image
      run: |
        docker build -t $REGISTRY/${{ env.IMAGE_NAME_WORKER }}:latest -f FiapServiceVideoProcessor.Worker/Dockerfile .
        docker push $REGISTRY/${{ env.IMAGE_NAME_WORKER }}:latest
