name: CI/CD - Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Clean previous build artifacts
      run: dotnet clean

    - name: Restore API dependencies
      run: dotnet restore FiapServiceVideoProcessor.csproj

    - name: Build API
      run: dotnet build FiapServiceVideoProcessor.csproj --configuration Release --no-restore

    - name: Publish Docker images
      run: |
        docker build -t dmiyamoto86/fiap-api -f FiapServiceVideoProcessor.WebApi/Dockerfile .
        docker build -t dmiyamoto86/fiap-worker -f FiapServiceVideoProcessor.Worker/Dockerfile .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push dmiyamoto86/fiap-api
        docker push dmiyamoto86/fiap-worker
